### ISSUE TITLE
about IP address

### ISSUE THREAD

**Issue by xrain0610** [zchee/docker-machine-driver-xhyve#62]
when i docker-machine restart default ,
the boot2docker ip will change,
and the env command is error.
can you fix it?

**Comment by zchee** [comment]
@xrain0610 Thanks issue :)

Yes, known issue.

e.g. when vm name is `xhyve`,
`docker-machine env xhyve` immediately after the `docker-machine restart xhyve`, an error will occur.
The reason is because `boot2docker` is in booting kernel.

If you wait for a little (e.g. 10sec), `docker-machine env xhyve` command to succeed?

**Comment by xrain0610** [comment]
@zchee  sorry , i file a wrong issue, 
i edit the /var/lib/boot2docker/profile and add --registry-mirror ,
then restart the machine, the docker is down .

**Comment by zchee** [comment]
@xrain0610 :)

but, It is valuable information. I'll remember that.
Thanks!
